package by.grsu.orel.controller;

import by.grsu.orel.Starter;
import by.grsu.orel.model.Routes;
import by.grsu.orel.model.Search;
import by.grsu.orel.repository.RouteRepository;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.Errors;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.io.Console;
import java.util.Map;

@Controller
@RequestMapping("/add")
public class AddController {

	private static final Logger logger = Logger.getLogger(Starter.class);

	@Autowired // This means to get the bean called routeRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private RouteRepository routeRepository;

	@PostMapping
	@ResponseBody
	public String handleJsonPostRequest(@RequestBody Map<String, Object> payload) {
		try {
			logger.info(payload.get("route"));
			logger.info(payload.get("name"));

			return "ok";
		} catch (Exception e) {
			return "suqua";
		}
	}
//	@PostMapping
//	public String receivePost(@RequestBody Search search) {
//
//		String pName = search.getpName();
//		String lName = search.getlName();
//
//		logger.info(pName);
//		logger.info(lName);
//		return "add";
//	}

	@GetMapping
	public String start(Model model) {
		return "add";
	}
}
