package by.grsu.orel.controller;

import by.grsu.orel.Starter;
import by.grsu.orel.model.Routes;
import by.grsu.orel.repository.RouteRepository;
import com.google.gson.Gson;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

/**
 * Controller for `/add` page
 */
@Controller
@RequestMapping("/add")
public class AddController {

    private static final Logger logger = Logger.getLogger(Starter.class);

    @Autowired // This means to get the bean called routeRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RouteRepository routeRepository;

    @PostMapping
    @ResponseBody
    public String handleJsonPostRequest(@RequestBody Map<String, Object> payload) {
        try {
//			logger.info(payload.get("route"));
//			logger.info(payload.get("name"));
            Routes route = new Routes();
            route.setName(payload.get("name").toString());
            route.setRoute(payload.get("route").toString());
//			logger.info(route.toString());

            routeRepository.save(route);
            return "route saved";
        } catch (Exception e) {
            return "route didn't save";
        }
    }

    @GetMapping
    public String start(Model model) {
        return "add";
    }
}
