package by.grsu.orel.controller;

import by.grsu.orel.Starter;
import by.grsu.orel.model.Routes;
import by.grsu.orel.repository.RouteRepository;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * Controller for `/` page
 */
@Controller
@RequestMapping("/")
public class IndexController {

    private static final Logger logger = Logger.getLogger(Starter.class);

    @Autowired // This means to get the bean called routeRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RouteRepository routeRepository;

    @RequestMapping(method = RequestMethod.GET)
    public String start(Model model) {

        Iterable<Routes> routesObject = routeRepository.findAll();
        model.addAttribute("routes", routesObject);

        return "index";
    }
}
