package by.grsu.orel.Controller;

import by.grsu.orel.Entity.Stop;
import by.grsu.orel.StopRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/demo2") // This means URL's start with /demo (after Application path)
public class StopController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StopRepository stopRepository;

    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser(@RequestParam String name
            , @RequestParam double longitude, @RequestParam double latitude) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Stop n = new Stop();
        n.setName(name);
        n.setLongitude(longitude);
        n.setLatitude(latitude);
        stopRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Stop> getAllUsers() {
        // This returns a JSON or XML with the users
        return stopRepository.findAll();
    }
}
